# .github/workflows/convert-lua-to-json.yml
name: Convert Lua to JSON

on:
  push:
    branches: [ main ]
    paths:
      - 'src/**.lua'  # Only trigger when Lua files in src directory change

jobs:
  convert:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      
      - name: Create data directory if it doesn't exist
        run: mkdir -p data
      
      - name: Run conversion script for guns
        if: hashFiles('src/guns.lua') != ''
        run: node scripts/lua-to-json.js src/guns.lua data/guns.json
      
      - name: Run conversion script for turrets
        if: hashFiles('src/turrets.lua') != ''
        run: node scripts/lua-to-json.js src/turrets.lua data/turrets.json
      
      - name: Run conversion script for hulls
        if: hashFiles('src/hulls.lua') != ''
        run: node scripts/lua-to-json.js src/hulls.lua data/hulls.json
      
      - name: Commit and push if there are changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add data/
          git diff --quiet && git diff --staged --quiet || git commit -m "Auto-update JSON files from Lua source"
          git push